### ISSUE TITLE
Xquartz not starting

### ISSUE THREAD

**Issue by enkl7** [TritonDataCenter/pkgsrc#329]
Machine: Macbook Air (m1)
OS: Monterey 12.2.1

I installed modular-xorg and modular-xorg-quartz from [https://pkgsrc.joyent.com/packages/Darwin/11.0/arm64/All/](url) which seems to automatically pull down all the dependencies to run a X server.

Launching startx warns that `/opt/pkg/bin/X` no such file or directory - and suggests to make a script or link to the appropriate X server (xquartz in this case). I then make a link in /opt/pkg/bin `ln -s /opt/pkg/bin/Xquartz X`. 

However `startx` gives me this error: 

```
/opt/pkg/bin/xinit: giving up
/opt/pkg/bin/xinit: unable to connect to X server: Connection refused
/opt/pkg/bin/xinit: server error
```

Xorg doesn't leave any log files so I don't know how to debug this.

Am I missing something here?
Would really appreciate any help to get a working X server.

**Comment by jperkin** [comment]
Note the message that is printed when installing `modular-xorg-xquartz`:

```
$ pkg_info -D modular-xorg-xquartz
Information for modular-xorg-xquartz-1.17.2nb6:

Install notice:
===========================================================================
$NetBSD: MESSAGE,v 1.1 2015/10/01 12:55:09 tnn Exp $

To finish the installation of pkgsrc X11 on your Mac:

$ sudo mv /Applications/Utilities/X11.app /Applications/Utilities/X11.app.bak
$ sudo ln -s /opt/pkg/Applications/Utilities/X11.app /Applications/Utilities

$ echo "/opt/pkg/bin/xterm &" > ~/.xinitrc
$ echo /opt/pkg/bin/quartz-wm >> ~/.xinitrc
$ /opt/pkg/bin/startx -- /opt/pkg/bin/Xquartz

You can also launch X11.app from finder instead of the last step.

===========================================================================
```

Note that the first two commands aren't actually required (I should fix the message file).  An easier way to launch it is, after making the necessary `~/.xinitrc` changes, to run:

```
$ open /opt/pkg/Applications/Utilities/X11.app
```

This works for me on Intel.  If you're still unable to launch using these instructions then it may be an Arm issue, and I'll try to reproduce on my M1 at some point.

**Comment by enkl7** [comment]
Thanks for the input @jperkin , unfortunately though the error still remains and X refuses to start.
